### PR TITLE
Fixed some typos in french translation

### PR DESCRIPTION
**Pull request by Nioub**
Just fixed some typos in the french translation.

Best regards,

### CODE REVIEW

**Comment by buxx** [comment]
Hello @Nioub , thank's for this patch.

@Skylsmoi or @PhilippeAccorsi Can you take a look about cypress test fail ? We have to determinate if test fail because the changes or if it is a "random fail". If it is a "random fail", please disable the test and open an issue to fix it. If it is a fail because changes, please fix the test.

**Comment by PhilippeAccorsi** [comment]
Issue exist here: #1327 
We need to discuss with @lebouquetin to define if we need to solve this issue for v2.2 or if we can disable this test.

**Comment by lebouquetin** [comment]
What happens if we restart the tests?

**Comment by PhilippeAccorsi** [comment]
Generally it works. Sometime we need to restart 2 or 3 time more.

**Comment by lebouquetin** [comment]
So you can accept the MR if you are pretty sure the failure comes from our unstable test case.

**Pull request merged**
