### PR TITLE
Refactor/941  remove group system for profile

### PR DESCRIPTION
**Pull request by inkhey**
related to #941 

Convert profile as Enum in users table. Remove completely "group" mecanism.

## Checkpoints

The goal of this section is to help code reviewer to do required checks on this pull request. Please don't edit this list.
If one or more of these checkpoints are out of scope, please write below why they are.

**For code reviewer**

- [x] Code is clear enough
- [x] If there are FIXME in the code, then there are associated issues and issue is referenced in the FIXME
- [x] If there are TODO, NOTE or HACK in code, date and developer initials are present
- [x] Automated tests have been written (covering feature or non regression), or *at least* an issue has been created for test implementation

**For developer**

- [x] Manual tests done to ensure stability on whole application layers, issue expectation follow
- [x] Original issue have been updated with a short resume of implemented solution

**For quality team**

- [x] Tested by quality team

### CODE REVIEW

**Comment by inkhey** [comment]
Refactoring is completed, but we need discussion (@lebouquetin) about future usage of Tracim to be sure this fix is a good idea.

**Comment by inkhey** [comment]
@lebouquetin About this refactoring, i suggest to merge this for Tracim 2.6.4 or 3.0 to have a cleaner code about profile. 
Customized profile/role with some kind of group feature may be cool but i do think we need lot of search to find a proper way to include this in tracim properly. 
Current code use a "Group" table that doesn't mean anything now.

What i see currently about a group feature:

1. Add a "function" field for user that match to function of the user, these function may be highly configurable and potentially mentionnable user (will just mention the user with the function which have access to tracim).
2. The same as before but with mecanism to: 
   - set default profile and workspace role to all user of a function at user creation/ add to function
   - ui to change easily all workspace role for all user with a specify function

this way we can show organization "role" (named function) without need to deal with role access in tracim.

We can of course imagine something more configurable but has we already have two level of right (per workspace and per user), i currently do no see a simple solution.

I suggest to create an issue with the beginning of thinking about this and merge this one.

**Comment by lebouquetin** [comment]
After discussion with a community of cities, there are some chances that we need to be able to configure things. So the right way to avoid technical debt would be to allow the full interface to be parameterized according to dynamic profiles and permissions.

We need to chat about this (what hard stuff you see) before to decide for this merge request; my point of view is probably more about making things more dynamic than about simplifying things.

**Comment by inkhey** [comment]
After discussion with @lebouquetin, we will merge this and create a new ticket about making things more configurable.

**Comment by inkhey** [comment]
1. about automatic test: there have been updated to follow the refacto, but no new test has been added. current test automatic for both migration and endpoint rely now on refactorised code to ensure no regression.
2. about manual test: rapid manual test of tracim with profile, manual test of migration code to ensure it work correctly on different database.

**Comment by buxx** [comment]
Manuel tests done: ready to merge.

**Pull request merged**
