### PR TITLE
chore: add commitlint

### PR DESCRIPTION
**Pull request by Haskaris**
Issue ref NA

This is a proposal:
Use commitlint, so every of our commit are the same. This way we can easily use [release-please](https://github.com/googleapis/release-please) which is a tool to generate release and changelog base on PRs.

Currently this force to use [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) messages. However we can add custom configuration to use Algoo's configuration (but then I'm not sure about [release-please](https://github.com/googleapis/release-please))

## Checkpoints

**For developers**

- [x] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [x] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
~~- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)~~
- [x] Make sure that:
  - if there are modifications in the Tracim configuration files (eg. `development.ini`), they are documented in `backend/doc/setting.md`
  - any migration process required for existing instances is documented
  - relevant people for these changes are notified
- [x] Original authors of the features included in a multi-feature branch (maintenance fixes -> develop, security fixes -> develop, …) should be part of the reviewers, especially if you encountered merge conflicts.

**For code reviewers**

- [x] The code is clear enough
- [x] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [x] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [ ] Manual, quality tests have been done

### CODE REVIEW

**Review by Skylsmoi — APPROVED** [review]

**Comment by Skylsmoi** [comment]
i'm not the best suited to review this changes, i'd prefer someone else to validate this pr before merging

**Comment by grignards** [comment]
Good idea. Could it be added to concourse CI too, so that commits from developers who aren't using `pre-commit` are still checked?

**Comment by lebouquetin** [comment]
This is a structuring change.

Questions:

- do we have at the moment the necessary rigor to make automatic release notes?
- What about rolled back / buggy PR? (ie when an issue is fixed through several PRs?)
- What about features implemented through several PR / several issues?

My feeling is this should be explicitly discussed as a team discussion, (not in a PR comment thread) with entire dev team, including advantages *and drawbacks*.

There was some discussions in the past about this; I'm not sure we should change things now. For example, how will you manage breaking changes?

My concerns are about release notes automatisation (we need to be clear and efficient on manually writing release notes before to think about automatisation), not about commit lint itself.

**Comment by Haskaris** [comment]
@grignards 
> Could it be added to concourse CI too, so that commits from developers who aren't using pre-commit are still checked?
I'm not sure about that. The idea of Commitlint is to _block_ the any commit that wouldn't follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) messages. We can still add custom configuration to use Algoo's configuration.

@lebouquetin 
Since your comment is about automatic release and not Commitlint, I'll report this in our Tracim instance.

**Comment by Skylsmoi** [comment]
could not set it to work.

I did:
- merge develop into branch
- fix merge conflicts
- fix pre-commit-config stage names (from commit to pre-commit and from merge-commit to pre-merge-commit)
- upgrade pre-commit in requirements-devtool.txt
- installed hook commit-msg
- add install hook commit-msg to doc

I now have errors installing alessandrojcm/commitlint-pre-commit-hook: "Found invalid rule names: header-trim"
This error isn't from our code, so it's from dependencies incompatibility

Won't investigate further, I'm closing the PR

**Pull request closed without merging**
