### PR TITLE
[2.6.X] add editorconfig file for python

### PR DESCRIPTION
**Pull request by inkhey**
related to #2631

## Checkpoints

The goal of this section is to help code reviewer to do required checks on this pull request. Please don't edit this list.
If one or more of these checkpoints are out of scope, please write below why they are.

- [x] Code is clear enough
- [x] If there are FIXME in the code, then there are associated issues and issue is referenced in the FIXME
- [x] If there are TODO, NOTE or HACK in code, date and developer initials are present
- [x] Automated tests have been written (covering feature or non regression), or *at least* an issue has been created for test implementation
- [x] Tested by quality team

### CODE REVIEW

**Comment by inkhey** [comment]
@Skylsmoi @metzgegu could you complete `.editorconfig ` with frontend rules (javascript, etc...) ?

**Comment by Skylsmoi** [comment]
> @Skylsmoi @metzgegu could you complete `.editorconfig ` with frontend rules (javascript, etc...) ?

.editorconfig files already exists for frontend. See comments in https://github.com/tracim/tracim/issues/2631

**Comment by inkhey** [comment]
No sure how we can test this, all i found is https://github.com/editorconfig-checker/editorconfig-checker to check consistency between editorconfig rules and code, which is another issue.

**Comment by gbonaspetti** [comment]
Tested and verified on branch.

**Pull request merged**
