### PR TITLE
[For 2.6.x] Fix/2679 Input and tinyMCE auto focus

### PR DESCRIPTION
**Pull request by metzgegu**
#2679 

I don't think tests are required here because it will test the feature of `input` and `tinyMCE` instead of `Tracim`

## Checkpoints

The goal of this section is to help code reviewer and merge request author to do required checks on this pull request. Please don't edit this list.
If one or more of these checkpoints are out of scope, please write below why they are.

**For code reviewer**

- [x] Code is clear enough
- [x] If there are FIXME in the code, then there are associated issues and issue is referenced in the FIXME
- [x] If there are TODO, NOTE or HACK in code, date and developer initials are present
- [x] Automated tests have been written (covering feature or non regression), or *at least* an issue has been created for test implementation

**For developper**

- [x] Manual tests done to ensure stability on whole application layers, issue expectation follow
- [x] Original issue have been updated with a short resume of implemented solution

**For quality team**

- [x] Tested by quality team

### CODE REVIEW

**Comment by Skylsmoi** [comment]
I agree with your no test suggestion.
I have a question though, app Html can have 2 tinyMce instance on the same page.
For the content and the comment. Can you confirm it works well ?

**Comment by metzgegu** [comment]
> I agree with your no test suggestion.
> I have a question though, app Html can have 2 tinyMce instance on the same page.
> For the content and the comment. Can you confirm it works well ?

Yes it works well, it focus the last tinyMce instance activated

**Comment by Skylsmoi** [comment]
nice

**Comment by gbonaspetti** [comment]
Tested and verified on branch.

**Pull request merged**
