### PR TITLE
fix(front): news re-render with each characters when writing title

### PR DESCRIPTION
**Pull request by floreal15**
https://github.com/tracim/tracim/issues/6408

## Checkpoints

**For developers**

- [x] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [x] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
- [x] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)
- [x] Make sure that:
  - if there are modifications in the Tracim configuration files (eg. `development.ini`), they are documented in `backend/doc/setting.md`
  - any migration process required for existing instances is documented
  - relevant people for these changes are notified
- [x] Original authors of the features included in a multi-feature branch (maintenance fixes -> develop, security fixes -> develop, …) should be part of the reviewers, especially if you encountered merge conflicts.

**For code reviewers**

- [x] The code is clear enough
- [x] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [x] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [x] Manual, quality tests have been done

### CODE REVIEW

**Review by Skylsmoi — CHANGES_REQUESTED** [review]
mmh I don't like creating a wrapper only to switch from an uncontrolled component to a controlled one.

I'd rather improve CardPopupCreateContent to be a controlled component.

Or, if it makes the component too complex, generalize PopupSetPublicationTitle as a ControlledCardPopupCreateContent.

The reason is that this issue probably exists in other places of tracim. Having a generic solution will makes us fix them more easily when we spot one.

**Comment by Millefeuille42** [comment]
about this @Skylsmoi this was my solution (and this is what I would've suggested @floreal15).

```
import React, {useState} from "react";
import {CardPopupCreateContent} from "tracim_frontend_lib";
import PropTypes from "prop-types";

const CardPopupCreateContentDriver = (props) => {
  const [contentName, setContentName] = useState(props.contentName)

  const handleValidate = () => {
    props.onValidate(contentName)
  }

  const handleChangeContentName = (e) => {
    setContentName(e.target.value)
  }

  return (
    <CardPopupCreateContent
      {...props}
      onValidate={handleValidate}
      onChangeContentName={handleChangeContentName}
      contentName={contentName}
      btnValidateLabel={contentName ? props.validateLabelEmpty : props.validateLabel}
    />
  )
}

CardPopupCreateContentDriver.propTypes = {
  validateLabelEmpty: PropTypes.string,
  validateLabel: PropTypes.string,
  contentName: PropTypes.string.isRequired,
  customColor: PropTypes.string,
  displayTemplateList: PropTypes.bool,
  faIcon: PropTypes.string,
  inputPlaceholder: PropTypes.string,
  onChangeTemplate: PropTypes.func,
  onClose: PropTypes.func.isRequired,
  onValidate: PropTypes.func.isRequired,
  label: PropTypes.string,
  allowEmptyTitle: PropTypes.bool,
  templateList: PropTypes.array
}

CardPopupCreateContentDriver.defaultProps = {
  validateLabelEmpty: '',
  validateLabel: '',
  customColor: '#333',
  displayTemplateList: false,
  faIcon: '',
  inputPlaceHolder: '',
  label: '',
  onChangeTemplate: () => {},
  allowEmptyTitle: false,
  templateList: []
}

export default CardPopupCreateContentDriver

```

We could do something like this

**Review by Millefeuille42 — CHANGES_REQUESTED** [review]
Same as @Skylsmoi + see comment above

**Comment by Skylsmoi** [comment]
it looks like what i was thinking

**Comment by floreal15** [comment]
Most app in tracim already have their own version of ControlledCardPopupCreateContent ( CardPopupCreateContent, CardPopupCreateContent, CardPopupCreateContent, CardPopupCreateContent, CardPopupCreateContent, ... ) and use those to create content
In the case of the news, part of the content came from Publication where content is wrote so the component is didn't create the new but only chose the title.
Due to that creating a ControlledCardPopupCreateContent might not be that usefull

**Review by Skylsmoi — APPROVED** [review]

**Review by Millefeuille42 — APPROVED** [review]

**Comment by Millefeuille42** [comment]
tested on branch

**Pull request merged**
