### PR TITLE
[#1928] adding search parameters at url

### PR DESCRIPTION
**Pull request by gbonaspetti**
#1928

## Checkpoints

The goal of this section is to help code reviewer to do required checks on this pull request. Please don't edit this list.
If one or more of these checkpoints are out of scope, please write below why they are.

- [x] Code is clear enough
- [x] If there are FIXME in the code, then there are associated issues and issue is referenced in the FIXME
- [x] If there are TODO, NOTE or HACK in code, date and developer initials are present
- [x] Automated tests have been written (covering feature or non regression), or *at least* an issue has been created for test implementation

### CODE REVIEW

**Comment by Skylsmoi** [comment]
It would be nice to have a cypress test for this feature.
A test that open an url with a query parameter and checks that there are some search results

**Comment by gbonaspetti** [comment]
> It would be nice to have a cypress test for this feature.
> A test that open an url with a query parameter and checks that there are some search results

There is already a similar issue for that (https://github.com/tracim/tracim/issues/1893). I'm gonna do it.

**Comment by gbonaspetti** [comment]
Blocked by https://github.com/tracim/tracim/issues/1973

**Comment by inkhey** [comment]
@gbonaspetti  #1973 merged.

**Pull request merged**
