### PR TITLE
chore(frontend): fail with noise when compilation fails

### PR DESCRIPTION
**Pull request by raphj**
#3989 

## Checkpoints

**For developers**

- [X] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [X] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
- [X] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)
- [x] Make sure that:
  - if there are modifications in the Tracim configuration files (eg. `development.ini`), they are documented in `backend/doc/setting.md`
  - any migration process required for existing instances is documented
  - relevant people for these changes are notified

**For code reviewers**

- [x] The code is clear enough
- [x] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [x] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [x] Manual, quality tests have been done

### CODE REVIEW

**Review by gbonaspetti — APPROVED** [review]

**Review by PhilippeAccorsi — APPROVED** [review]

**Comment by PhilippeAccorsi** [comment]
@raphj do you have an idea to test this ? (what can be done to make sure compile failed ?)

**Comment by raphj** [comment]
@PhilippeAccorsi Yes, you need to introduce an error in one of the javascript files. for instance edit file `frontend_app_thread/src/index.js` and add `LOL` at the end of the first line.

**Comment by PhilippeAccorsi** [comment]
> @PhilippeAccorsi Yes, you need to introduce an error in one of the javascript files. for instance edit file `frontend_app_thread/src/index.js` and add `LOL` at the end of the first line.

Thanks. I tried to test this fix today or tomorrow.

**Comment by PhilippeAccorsi** [comment]
Tested manually with build_full_frontend.sh but not tested with docker images.

**Comment by PhilippeAccorsi** [comment]
Tested also with docker build command.

**Review by PhilippeAccorsi — APPROVED** [review]
Good for me

**Pull request merged**
