### PR TITLE
disable email.notification.processing_mode feature, set it always as sync

### PR DESCRIPTION
**Pull request by inkhey**
related to #1161

### CODE REVIEW

**Comment by buxx** [comment]
Why disable asynchronus email sending feature @inkhey @lebouquetin ?

**Comment by buxx** [comment]
> Why disable asynchronus email sending feature @inkhey @lebouquetin ?

If it is related to #1345 , please make a reference into #1161 .

**Comment by inkhey** [comment]
> Why disable asynchronus email sending feature @inkhey @lebouquetin ?

This is not asynchronous mail sending but another feature, there is actually 2 level of asynchronous for email notification but this one (asynchronous for mail notification building) isn't implemented and create only trouble when reading configuration file.

**Comment by buxx** [comment]
> but this one (asynchronous for mail notification building) isn't implemented and create only trouble when reading configuration file.

Ok, thank's for precisions !

**Comment by inkhey** [comment]
@lebouquetin It's not never read, but it exist only one valid value. As this issue is to not show the parameter, i didn't wanted to add modification to the way it was handled internally.

**Pull request merged**
