### PR TITLE
fix: set max size for mobile email helper popin

### PR DESCRIPTION
**Pull request by Millefeuille42**
#6479

## Checkpoints

**For developers**

- [x] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [x] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
- [x] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)
- [x] Make sure that:
  - if there are modifications in the Tracim configuration files (eg. `development.ini`), they are documented in `backend/doc/setting.md`
  - any migration process required for existing instances is documented
  - relevant people for these changes are notified
- [x] Original authors of the features included in a multi-feature branch (maintenance fixes -> develop, security fixes -> develop, …) should be part of the reviewers, especially if you encountered merge conflicts.

**For code reviewers**

- [x] The code is clear enough
- [x] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [x] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [x] Manual, quality tests have been done

### CODE REVIEW

**Review by floreal15 — APPROVED** [review]
if PopoverHelperBody isn't use in any other place approved

**Comment by Millefeuille42** [comment]
@floreal15 It is used elsewhere, but it is all in the same usage context, tested all 2 cases (email and web notification) in mobile and web and it worked

**Comment by Millefeuille42** [comment]
For the tester:
- Set the navigator in responsive mode, with low height (like 600px), and for a mobile phone (pick one of the phone presets)
- Create / join a space
- Click on the helper icon next to the email followup picker
- The popin should not be cut or should be scrollable otherwise

**Comment by Millefeuille42** [comment]
Original issue was about vertical cutting, I think we can merge this but we should make an issue to address this specific problem

**Comment by floreal15** [comment]
Yes, I have tested in branch, the vertical cutting is fixed

**Comment by Millefeuille42** [comment]
https://github.com/tracim/tracim/issues/6563

**Pull request merged**
