### PR TITLE
fix(frontend): stabilize kanbans

### PR DESCRIPTION
**Pull request by Haskaris**
Issue #5153

## Checkpoints

**For developers**

- [x] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [x] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
- [x] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)
- [x] Make sure that:
  - if there are modifications in the Tracim configuration files (eg. `development.ini`), they are documented in `backend/doc/setting.md`
  - any migration process required for existing instances is documented
  - relevant people for these changes are notified
- [x] Original authors of the features included in a multi-feature branch (maintenance fixes -> develop, security fixes -> develop, …) should be part of the reviewers, especially if you encountered merge conflicts.

**For code reviewers**

- [x] The code is clear enough
- [x] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [x] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [x] Manual, quality tests have been done

### CODE REVIEW

**Comment by Haskaris** [comment]
https://github.com/tracim/tracim/pull/6168/commits/f504e9b4a4a1b68f8c4a76f191ad7fd078145df2 because adding mention is a bit more work than just enable mention in KanbanCardEditor.jsx

**Comment by PhilippeAccorsi** [comment]
I think this fix is a bugfix for tracim 4.5.x so maybe better to merge in maintenance branch.

**Comment by Haskaris** [comment]
Indeed. However the maintenance branch doesn't exist yet. If you can create it I can change the destination branch.

**Comment by Haskaris** [comment]
PR Updated

**Comment by buxx** [comment]
Hi @Haskaris We just noticed this PR ! Will take a look !

**Review by Skylsmoi — APPROVED** [review]

**Comment by Skylsmoi** [comment]
mentions doesn't work because props isMentionEnabled is still at false
Tried to set it to true, mentions autocomplete works but mention isn't received by user
I'm assuming the backend doesn't parse it
Won't fix for now, mention still won't work in app kanban

**Comment by Skylsmoi** [comment]
The PR adds TLM handling for app kanban and rename the "value" label to "Open field"

**Pull request merged**
