### PR TITLE
add better validator for max length of database fields

### PR DESCRIPTION
**Pull request by inkhey**
related to #4718

:warning: Add a frontend part ?

## Checkpoints

**For developers**

- [x] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [x] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
- [x] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)
- [x] Make sure that:
  - if there are modifications in the Tracim configuration files (eg. `development.ini`), they are documented in `backend/doc/setting.md`
  - any migration process required for existing instances is documented
  - relevant people for these changes are notified
- [x] Original authors of the features included in a multi-feature branch (maintenance fixes -> develop, security fixes -> develop, …) should be part of the reviewers, especially if you encountered merge conflicts.

**For code reviewers**

- [x] The code is clear enough
- [x] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [x] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [x] Manual, quality tests have been done

### CODE REVIEW

**Review by raphj — APPROVED** [review]

**Comment by raphj** [comment]
The frontend part is handling the specific "tag name to long" 400 error, right?
If I have some time this afternoon I can work on this, this is short enough.

**Comment by inkhey** [comment]
> The frontend part is handling the specific "tag name to long" 400 error, right? If I have some time this afternoon I can work on this, this is short enough.

The error code is not specific to size (generic validation error), This backend code force backend to failed directly with 400 validation error for : 
- tag too long (>255)
- content label too long (>1024)
- workspace label too long (>1024)
- reaction value too long (>255)
I'm not sure how the frontend should handled these, but it should be a bit more explicit.

**Comment by raphj** [comment]
I guess we are good for now then, if the error code is generic there's not much else we can do in the frontend more than showing a generic error message like is probably already shown now. Let's send this PR to manual tests though.

**Review by grignards — APPROVED** [review]

**Comment by inkhey** [comment]
To test this:
- try create/update a > 1024 characters workspace.
- try create a > 256 tag.
- try create/update a > 1024 content label.

**Comment by gbonaspetti** [comment]
Tested on branch

**Pull request merged**
