### PR TITLE
Feat/4562 move language into account settings

### PR DESCRIPTION
**Pull request by gbonaspetti**
#4562 
#5452

## Checkpoints

**For developers**

- [x] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [x] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
- [x] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)
- [x] Make sure that:
  - if there are modifications in the Tracim configuration files (eg. `development.ini`), they are documented in `backend/doc/setting.md`
  - any migration process required for existing instances is documented
  - relevant people for these changes are notified
- [x] Original authors of the features included in a multi-feature branch (maintenance fixes -> develop, security fixes -> develop, …) should be part of the reviewers, especially if you encountered merge conflicts.

**For code reviewers**

- [x] The code is clear enough
- [x] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [x] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [x] Manual, quality tests have been done

To test:
- Test if we can still change the language on unlogged pages
- Test if the bug #5452 still happens
- The admin should not be able to change an user language
- The user should be able to change its own language

Note: the follow bug is not linked to this development and it exists already 
- open two tabs
- at tab 1 open a content
- at tab 2 changes the language
- the content on tab 1 will not be changed (but the header will)

### CODE REVIEW

**Comment by inkhey** [comment]
I did some try with 2 concurrent tabs, in some unclear case, i have :
- file app in a LTR language (portuguese) but with RTL ui
- other part of the ui (sidebar/headbar) in arabic (and in RTL).

**Comment by gbonaspetti** [comment]
> I did some try with 2 concurrent tabs, in some unclear case, i have :
> 
> * file app in a LTR language (portuguese) but with RTL ui
> * other part of the ui (sidebar/headbar) in arabic (and in RTL).

@inkhey this is not related with the note on description?
> Note: the follow bug is not linked to this development and it exists already
> * open two tabs
> * at tab 1 open a content
> * at tab 2 changes the language
> * the content on tab 1 will not be changed (but the header will)

**Comment by inkhey** [comment]
@gbonaspetti To reproduce the issue:

- open 2 tab with a language A:
  - tab1 in a content
  - tab 2 in langage selection tab 
- change language to B in tab 2
- Case A: - sidebar and headbar are switch to language B in tab 1
- Case B: - sidebar and headbar don't change (still language A

After this, if we change language to C in tab 2 :
- Case A: - sidebar and headbar are switched to language C in tab 1
- Case B: - sidebar and headbar are switch to language B in tab 1 (the precedently chosen language)

I don't know the reason why sometime we are in case A and sometime in case B . case B appears most of the time in my own computer.

**Review by raphj — APPROVED** [review]

**Comment by knodelle** [comment]
> @gbonaspetti To reproduce the issue:
> 
>     * open 2 tab with a language A:
>       
>       * tab1 in a content
>       * tab 2 in langage selection tab
> 
>     * change language to B in tab 2
> 
>     * Case A: - sidebar and headbar are switch to language B in tab 1
> 
>     * Case B: - sidebar and headbar don't change (still language A
> 
> 
> After this, if we change language to C in tab 2 :
> 
>     * Case A: - sidebar and headbar are switched to language C in tab 1
> 
>     * Case B: - sidebar and headbar are switch to language B in tab 1 (the precedently chosen language)
> 
> 
> I don't know the reason why sometime we are in case A and sometime in case B . case B appears most of the time in my own computer.

I'm not reproducing this bug

**Comment by gbonaspetti** [comment]
An issue was made fir the issue https://github.com/tracim/tracim/issues/5468

**Comment by knodelle** [comment]
tested on branch

**Pull request merged**
