### PR TITLE
fix(frontend): better naming and list comparing

### PR DESCRIPTION
**Pull request by gbonaspetti**
#6040 

## Checkpoints

**For developers**

- [x] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [x] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
- [x] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)
- [x] Make sure that:
  - if there are modifications in the Tracim configuration files (eg. `development.ini`), they are documented in `backend/doc/setting.md`
  - any migration process required for existing instances is documented
  - relevant people for these changes are notified
- [x] Original authors of the features included in a multi-feature branch (maintenance fixes -> develop, security fixes -> develop, …) should be part of the reviewers, especially if you encountered merge conflicts.

**For code reviewers**

- [x] The code is clear enough
- [x] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [x] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [x] Manual, quality tests have been done

### CODE REVIEW

**Review by Skylsmoi — APPROVED** [review]
I'm approving the PR since this is a proper way of comparing 2 lists
But, I wonder about the processing time this might require.
Because it requires to convert an entire array of object into a string then compare these strings.
I think this must be tested specifically during the tests on branch for this PR

**Comment by Skylsmoi** [comment]
### For the person who test this PR on branch
A special attention should be set on cpu consumption on this branch.
Some tests must be done with a big list of comments, spaces and at least a space with a lot of contents

**Review by Haskaris — APPROVED** [review]

**Comment by Haskaris** [comment]
So I was testing this PR with ~100 spaces, ~100 contents and ~100 comments
The thing is, I don't believe that 100 of each are enough to be considered as "a lot" (it can be a lot for a human but not that much for a computer)
Therefore I went digging for "a proper way to compare 2 lists"
And I found this [thread](https://stackoverflow.com/questions/7837456/how-to-compare-arrays-in-javascript) on StackOverflow. It speaks about how to compare arrays (lists) in js.

It appears that `JSON.stringify` works and is the simplest way, but will introduce lags on big data.

There are other solutions:
 - We can recreate the wheel by creating our own function to compares our array (see [first answer](https://stackoverflow.com/a/14853974) or [second answer](https://stackoverflow.com/a/19746771))
 - We can use `Underscode` or `Lodash` `isEqual` function

I'd suggest to use `Lodash` `isEqual` function since we already use it (see `Tracim.jsx > Tracim > handleheadTitleAndFavicon > hasHeadTitleChanged`)

[Someone did some statistics about fast/slow](https://stackoverflow.com/a/42186143)

**Review by Haskaris — CHANGES_REQUESTED** [review]
Use `isEqual` from `Lodash` to compare lists

**Comment by Skylsmoi** [comment]
What scares me is that we are doing array comparison on each component updates, and there might be a lot of component updates especially during first page load.

Also, when we do `props.workspaceContentList !== prevProps.workspaceContentList` on WorkspaceContent.jsx, we are comparing the pointer but since this props comes from redux, we know it's a new pointer when it gets updated. So, I think the previous way (without isEqual()), in that case, should be enough.

This PR points to another PR, what was the purpose of refactoring the arrays comparisons again please?

**Comment by gbonaspetti** [comment]
> This PR points to another PR, what was the purpose of refactoring the arrays comparisons again please?

Hello, remembering the context: this PR points to another PR because it was created to address revision requests made after the PR was merge (ref https://github.com/tracim/tracim/pull/6040#issuecomment-1345626951), the initial issue is https://github.com/tracim/tracim/issues/6030.

In this PR (6040) the sort of lists was added and the idea was that it would only be necessary to redo the sort (i.e. run the function setDisplayedXXXXXXXXList) and update the state of the displayed list, if the list sent by props to the component changed.

**Review by Haskaris — APPROVED** [review]

**Review by Skylsmoi — APPROVED** [review]

**Comment by Millefeuille42** [comment]
This PR seems to be still relevant, I will test it soon

**Comment by PhilippeAccorsi** [comment]
I think this fix is a bugfix for tracim 4.5.x so maybe better to merge in maintenance branch.

**Comment by Haskaris** [comment]
Indeed. However the maintenance branch doesn't exist yet. If you can create it I can change the destination branch.

**Comment by Millefeuille42** [comment]
> Indeed. However the maintenance branch doesn't exist yet. If you can create it I can change the destination branch.

I created a maintenance/4.5 branch, if that's what you asked for

**Comment by Haskaris** [comment]
Sorry, this was a copy pasta to answer the comments... I'm not responsible of this PR. I'll update mines.

**Comment by lebouquetin** [comment]
@Skylsmoi do you have an idea of what should be done with this issue? Should we close it? delay it to tracim 4.8? No idea?

**Comment by Skylsmoi** [comment]
I think that it must be tested to check the performance impact of these changes.
If it's not that an issue, I think this PR should be merge since it seems to fix bugs.

Eventually, we can merge it and test it on our own instances, we should be able to judge see if there is a reduction in performance.
But all the team should be aware that there is a potentially performance impactful change and be prepared to revert the PR if required

**Comment by lebouquetin** [comment]
I merge it into develop so that we have it for 4.7 release in a few days/weeks. We'll test it and rollback if bugs or latency appear

**Pull request merged**
