### PR TITLE
[For 2.7.4] Log authenticated user

### PR DESCRIPTION
**Pull request by grignards**
This PR adds a log when an HTTP request is made by an authenticated user.
The log includes the request method, path and user id.

Related to #3043

## Checkpoints

The goal of this section is to help code reviewers and the merge request author to do the required checks on this pull request. Please don't edit this list.
If one or more of these checkpoints are out of scope, please write below why they are.

**For code reviewers**

- [x] The code is clear enough
- [x] If there are FIXMEs in the code, then there are associated issues and issue is referenced in the FIXME
- [x] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present
- [x] Automated tests have been written (covering the feature or non regression), or *at least* an issue has been created to implement the test

**For developers**

- [x] Manual tests done to ensure stability on whole application layers, issue expectation follow
- [x] The original issue has been updated with a short summary of the implemented solution

**For the quality team**

- [x] Tested by the quality team

### CODE REVIEW

**Comment by lebouquetin** [comment]
@grignards I suggest you put the data in a JSON format, what do you think ? It may be easier for parsing logs?

**Comment by PhilippeAccorsi** [comment]
I'm not sure but all new log starting with date like other log, or not ?

**Comment by inkhey** [comment]
> I'm not sure but all new log starting with date like other log, or not ?

It's the same logger as other tracim, so yes, similar format with date.

**Comment by PhilippeAccorsi** [comment]
> > I'm not sure but all new log starting with date like other log, or not ?
> 
> It's the same logger as other tracim log, so yes, similar format with date.

Ok, great.

**Comment by grignards** [comment]
> @grignards I suggest you put the data in a JSON format, what do you think ? It may be easier for parsing logs?

Here the proper solution would be to have structured logs, but as the current tracim logging outputs lines of text I think parsing the lines will be enough.
They are output in this form:
```
2020-05-13 09:00:52 INFO  [tracim:45][waitress] [TracimRequest] GET /api/v2/users/me/workspaces/1/contents/read_status from authenticated user 1
```

**Comment by lebouquetin** [comment]
@grignards ok. I suggest at least a specific keyword which will allow to distinguish these logs from others (to be sure not parsing some other log that match the pattern).

For example something like: 

```
2020-05-13 09:00:52 INFO  [tracim:45][waitress] [TracimRequest] GET /api/v2/users/me/workspaces/1/contents/read_status from authenticated user 1 #USERACTIVITY`
```

**Comment by PhilippeAccorsi** [comment]
Logging have same syntax with uwsgi ? (production use uwsgi on docker image).

**Comment by grignards** [comment]
> Logging have same syntax with uwsgi ? (production use uwsgi on docker image).

Yes from what I gathered with the log file you provided me.

**Comment by grignards** [comment]
In fact the `[TracimRequest]` part is already specific to those logs so we can use it to differentiate them.

**Comment by lebouquetin** [comment]
> In fact the [TracimRequest] part is already specific to those logs so we can use it to differentiate them.

I missed this. :+1:

**Comment by PhilippeAccorsi** [comment]
Test not to be necessary for this fix.

**Comment by PhilippeAccorsi** [comment]
@grignards you can squash and merge. Add `Ref: #3043` in message commit.

**Pull request merged**
