### PR TITLE
Fix/3526 look of the state wrapper in app file

### PR DESCRIPTION
**Pull request by raphj**
#3526 

## Checkpoints

**For developers**

- [x] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [x] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
- [x] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)

**For code reviewers**

- [x] The code is clear enough
- [x] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [x] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [x] Manual, quality tests have been done

### CODE REVIEW

**Comment by raphj** [comment]
The failing test is the unstable one. Other tests pass.

**Review by gbonaspetti — APPROVED** [review]

**Comment by gbonaspetti** [comment]
> The failing test is the unstable one. Other tests pass.

@raphj Can you disable this test with a comment linked to an issue du type "fix unstable test"?

**Review by grignards — APPROVED** [review]

**Comment by raphj** [comment]
> @raphj Can you disable this test with a comment linked to an issue du type "fix unstable test"?

done

**Comment by gbonaspetti** [comment]
Tested on branch

**Pull request merged**
