### PR TITLE
Feat/6030  sort by

### PR DESCRIPTION
**Pull request by gbonaspetti**
#6030 

## Checkpoints

**For developers**

- [x] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
~- [ ] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution~
~- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)~
- [x] Make sure that:
  - if there are modifications in the Tracim configuration files (eg. `development.ini`), they are documented in `backend/doc/setting.md`
  - any migration process required for existing instances is documented
  - relevant people for these changes are notified
- [x] Original authors of the features included in a multi-feature branch (maintenance fixes -> develop, security fixes -> develop, …) should be part of the reviewers, especially if you encountered merge conflicts.

**For code reviewers**

- [x] The code is clear enough
- [x] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [x] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [ ] Manual, quality tests have been done

### CODE REVIEW

**Review by Millefeuille42 — APPROVED** [review]

**Comment by Millefeuille42** [comment]
For unit tests:

Errors from `frontend_lib/test/helper.spec.js`: You removed functions from `frontend_lib/src/helper.js`

- sortWorkspaceList
- sortTimelineByDate

Errors from `frontend/test/src/helper.spec.js`: You removed a function from `frontend/src/util/helper.js`

- sortContentList

Errors from `frontend_app_workspace/test/container/PopupCreateWorkspace.spec.js`: Unable to identify cause: `n.replaceAll is not a function`

---

I don't think I could fix tests myself since they are due to removals.

**Comment by Millefeuille42** [comment]
Tested on branch.

**Comment by gbonaspetti** [comment]
@Skylsmoi I fixed your reviews requests at #6066

**Comment by Skylsmoi** [comment]
thx a lot o/

**Pull request merged**
