### PR TITLE
misc(documentation): refactoring documentation architecture

### PR DESCRIPTION
**Pull request by PhilippeAccorsi**
Issue https://github.com/tracim/tracim/issues/2912

This job is needed after this teamwork [(cf 04/07/2024 and "Arborescence documentation tracim")](https://algoo.tracim.fr/ui/workspaces/711/contents/html-document/155966)

## Checkpoints

**For developers**

- [x] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [x] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
- [x] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)
- [x] Make sure that:
  - if there are modifications in the Tracim configuration files (eg. `development.ini`), they are documented in `backend/doc/setting.md`
  - any migration process required for existing instances is documented
  - relevant people for these changes are notified
- [x] Original authors of the features included in a multi-feature branch (maintenance fixes -> develop, security fixes -> develop, …) should be part of the reviewers, especially if you encountered merge conflicts.

**For code reviewers**

- [x] The code is clear enough
- [x] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [x] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [x] Manual, quality tests have been done

### CODE REVIEW

**Comment by PhilippeAccorsi** [comment]
@lebouquetin @Skylsmoi I have created the architecture of documentation and moving file where I think it is the good place.

Questions: 
- Can you check naming of folders to purpose modification if necessary ? (i'm not sure about all folder naming)
- Are you ok to no more use uppercase in filename ? (this is an old rule to name file in UNIX system ? (to improve visibility with ls command, but it is not the case now. In Ubuntu ls no show UPPERCASE filename in the beginning of the list)
- Do we need to transfer all docker documentation from `tool_docker/` to new architecture ?

**Review by Skylsmoi — CHANGES_REQUESTED** [review]
changes looks good.
Only 2 things:
- I don't think the folder "how_does_it_works" from mentions/ serve anything and can be removed
- since images in developments/logos have moved, links to these files must be updated in README.md

**Comment by lebouquetin** [comment]
If you keep `how_does_it_works` , then rename it to `how_it_works`

**Comment by lebouquetin** [comment]
licences should be at the root, not in development part.

**Comment by Skylsmoi** [comment]
I agree for live_message_setup.md to be in development/

For the socket.md, I'm not sure because the tlm doc includes the doc related to messages that are used by other endpoints (eg. /api/users/:user_id/messages used to create notification wall)
The socket is about TLM but the TLM are about messages

**Comment by PhilippeAccorsi** [comment]
Thanks for your answer.
What do you think: I create folder tlm in development or just put some file directly in development folder ?

**Comment by Skylsmoi** [comment]
@PhilippeAccorsi I'm going to do it to have time to make the build today

**Comment by Skylsmoi** [comment]
What I did:
- created the file socket.md with "wip" and telling the see live_message_setup.md
- moved tlm/ into development/
- moved mention.md into development/ because it doesn't talk about api at all
- moved licenses/ into docs/ (root of docs)
- updated links to logo in README.md

**Review by Skylsmoi — APPROVED** [review]

**Review by floreal15 — APPROVED** [review]

**Comment by PhilippeAccorsi** [comment]
Thanks @Skylsmoi and @floreal15

**Pull request merged**
