### PR TITLE
Minio encryption - documentation

### PR DESCRIPTION
**Pull request by PhilippeAccorsi**
This is an old branch but all information not exist in Tracim repo.
I think information lost when we done Min.IO support.

## Checkpoints

**For developers**

- [x] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [x] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
- [x] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)
- [x] Make sure that:
  - if there are modifications in the Tracim configuration files (eg. `development.ini`), they are documented in `backend/doc/setting.md`
  - any migration process required for existing instances is documented
  - relevant people for these changes are notified
- [x] Original authors of the features included in a multi-feature branch (maintenance fixes -> develop, security fixes -> develop, …) should be part of the reviewers, especially if you encountered merge conflicts.

**For code reviewers**

- [x] The code is clear enough
- [x] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [x] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [x] Documentation done in 2020. Tested 2022/09/26 but some line missing or minio documentation change. Need some modification but workflow seems to be the same.

### CODE REVIEW

**Comment by PhilippeAccorsi** [comment]
@grignards do you remember something about this documentation ? I think we lost information about this PR, but I think it is important to merge this.

**Comment by grignards** [comment]
It seems relevant to me, we can merge it I think (after testing that the described steps are functional).

**Comment by PhilippeAccorsi** [comment]
Ok. I tried to check that this week. Thanks for your answer.

**Comment by PhilippeAccorsi** [comment]
@grignards I think some changes are necessary. I purpose to merge like that and we can improve documentation later. I have checked today and documentation of minio is better now, so maybe some other change are necessay or some step is more clear or more simple.

@Haskaris @buxx do you are agree with that ?

FYI : last commit is from `2020/12/31`

**Comment by buxx** [comment]
I agree

**Pull request merged**
