### PR TITLE
[For 3.0.0] Feature/1839 Custom form app

### PR DESCRIPTION
**Pull request by metzgegu**
#1839

This PR is here to merge `custom form` code unlinked to the frontend or backend, the feature will really added later

- [x] update this PR with new yarn changes

## Checkpoints

The goal of this section is to help code reviewer and merge request author to do required checks on this pull request. Please don't edit this list.
If one or more of these checkpoints are out of scope, please write below why they are.

**For code reviewer**

- [x] Code is clear enough
- [x] If there are FIXME in the code, then there are associated issues and issue is referenced in the FIXME
- [x] If there are TODO, NOTE or HACK in code, date and developer initials are present
- [x] Automated tests have been written (covering feature or non regression), or *at least* an issue has been created for test implementation

**For developper**

- [x] Manual tests done to ensure stability on whole application layers, issue expectation follow
- [x] Original issue have been updated with a short resume of implemented solution

**For quality team**

- [x] Tested by quality team

### CODE REVIEW

**Comment by Skylsmoi** [comment]
@metzgegu your this.skip() comments in cypress tests must be of type "TODO" and should be associated with an issue in this repo about "activating" the app. It can be an existing one.

Apart from that, I'm wondering what to do with the app admin. I'm not a fan of having dead code in it, but I currently don't know how to do otherwise.

We will need to discuss this

**Comment by Skylsmoi** [comment]
@lebouquetin The PR adds some code to the app feature admin. It's the forms that allow the creation of the custom forms.
While having dead code in a project isn't ideal, it's fine if it is only located in the same folder.
Here, we will have dead code in the app admin.

I don't know if it is still a good idea to merge it.

I'd like your advises on that

**Comment by Skylsmoi** [comment]
see issue description to know what have been decided

**Comment by Skylsmoi** [comment]
I'm checking the checkbox because we can't apply these rules properly for this PR.

We can't test this PR

**Comment by PhilippeAccorsi** [comment]
Not merge before release 2.7.0

**Comment by metzgegu** [comment]
Before merge, this PR need to be update with Yarn when #2873 is merged

**Pull request merged**
