### PR TITLE
Feat/5199  scroll by dragging cards

### PR DESCRIPTION
**Pull request by gbonaspetti**
#5199 

## Checkpoints

**For developers**

- [x] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [x] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
~- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)~ Automated tests for kanban at #5153 
- [x] Make sure that:
  - if there are modifications in the Tracim configuration files (eg. `development.ini`), they are documented in `backend/doc/setting.md`
  - any migration process required for existing instances is documented
  - relevant people for these changes are notified
- [x] Original authors of the features included in a multi-feature branch (maintenance fixes -> develop, security fixes -> develop, …) should be part of the reviewers, especially if you encountered merge conflicts.

**For code reviewers**

- [x] The code is clear enough
- [x] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [x] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [x] Manual, quality tests have been done

### CODE REVIEW

**Review by grignards — APPROVED** [review]

**Comment by grignards** [comment]
@gbonaspetti I found a little glitch during tests when dragging a card on the "new column" part of the board:
card-drag

It's not very important so feel free to ignore it if it seems difficult to solve.

**Comment by gbonaspetti** [comment]
> @gbonaspetti I found a little glitch during tests when dragging a card on the "new column" part of the board: !
> ...
> It's not very important so feel free to ignore it if it seems difficult to solve.

Thx, for me it's the expected behavior (drop the card anywhere other than a column returns the card to the original column), but I'm gonna wait for a validation from @charline-rageade before merge.

**Comment by grignards** [comment]
> > @gbonaspetti I found a little glitch during tests when dragging a card on the "new column" part of the board: !
> > ...
> > It's not very important so feel free to ignore it if it seems difficult to solve.
> 
> Thx, for me it's the expected behavior (drop the card anywhere other than a column returns the card to the original column), but I'm gonna wait for a validation from @charline-rageade before merge.

Yes, for me too, but the card first comes back in the last column, then to its original column. It's not very visible in the .gif, but obvious when doing it. I should have described the glitch better.

**Comment by gbonaspetti** [comment]
> > > @gbonaspetti I found a little glitch during tests when dragging a card on the "new column" part of the board: !
> > > ...
> > > It's not very important so feel free to ignore it if it seems difficult to solve.
> > 
> > 
> > Thx, for me it's the expected behavior (drop the card anywhere other than a column returns the card to the original column), but I'm gonna wait for a validation from @charline-rageade before merge.
> 
> Yes, for me too, but the card first comes back in the last column of the board, then to its original column. It's not very visible in the .gif, but obvious when doing it. I should have described the glitch better.

Oh sorry, yes, now I see, I'm gonna investigate the behavior. Thank you

**Comment by gbonaspetti** [comment]
@grignards unfortunately I have not had much success in my investigations, so I propose merge like this

**Comment by grignards** [comment]
Tested on branch.

**Pull request merged**
