### PR TITLE
Feat: Allow SAML single logout

### PR DESCRIPTION
**Pull request by Millefeuille42**
#6211

~~This PR comes from #6234 so they need to be merged in order, ideally~~ EDIT: Done

## Checkpoints

**For developers**

- [x] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [x] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
- [x] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)
- [x] Make sure that:
  - if there are modifications in the Tracim configuration files (eg. `development.ini`), they are documented in `backend/doc/setting.md`
  - any migration process required for existing instances is documented
  - relevant people for these changes are notified
- [x] Original authors of the features included in a multi-feature branch (maintenance fixes -> develop, security fixes -> develop, …) should be part of the reviewers, especially if you encountered merge conflicts.

**For code reviewers**

- [x] The code is clear enough
- [x] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [x] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [x] Manual, quality tests have been done

### CODE REVIEW

**Comment by Millefeuille42** [comment]
This lacks the support of IdP originated logout requests, since the deletion of the session is tied to the session itself.

A solution could be to look for the target `UserId` and logout the user linked to said `UserId`.

However, this use case do not seem much common nowadays.

**Comment by lebouquetin** [comment]
@Millefeuille42 the SAML related routes are not available in the swagger API documentation. I'm afraid this is because routes are not starting with `/api`

We need these routes to be documented (And I believe swagger is the place to do so).

**Comment by Millefeuille42** [comment]
@lebouquetin I have little to no knowledge on how it works yet, I need to check how swagger's elements are generated.

**Comment by lebouquetin** [comment]
@Millefeuille42 did you look at the way we generate swagger documentation ? (this is based on hapic)

If you didn't - or didn't find/understand, I suggest you add a markdown documentation for SAML related API documentation and add some TODO in the source code in order we upgrade the way the auto-generated documentation works.

Maybe in the future we'll have to move the routes to be part of `/api`; I'm pretty sure we should not make this right now

**Comment by Millefeuille42** [comment]
@lebouquetin not yet unfortunately. Legit question does SAML routes really needs documentation more than listing that the routes exists ? Since it is a standard. I'm not asking this in order to discredit what you ask, just because I'm curious.

**Comment by Millefeuille42** [comment]
@lebouquetin I added documentation and a TODO about it.

**Comment by lebouquetin** [comment]
I did check everything, even if I did not really test. We plan to test it on next days in preprod environment.

**Pull request merged**
