### PR TITLE
feat(backend): update supported version of python

### PR DESCRIPTION
**Pull request by Millefeuille42**
https://github.com/tracim/tracim/issues/6360

## Checkpoints

**For developers**

- [ ] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [ ] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)
- [ ] Make sure that:
  - if there are modifications in the Tracim configuration files (eg. `development.ini`), they are documented in `backend/doc/setting.md`
  - any migration process required for existing instances is documented
  - relevant people for these changes are notified
- [ ] Original authors of the features included in a multi-feature branch (maintenance fixes -> develop, security fixes -> develop, …) should be part of the reviewers, especially if you encountered merge conflicts.

**For code reviewers**

- [ ] The code is clear enough
- [ ] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [ ] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [ ] Manual, quality tests have been done

### CODE REVIEW

**Comment by Millefeuille42** [comment]
A tag: [feat_6360__update_supported_version_of_python](https://hub.docker.com/layers/algooci/tracim/feat_6360__update_supported_version_of_python/images/sha256-1bf85377678b9dfffc5caf970ddde5615d164112e6e29ee2abe6a9ef94500452?context=explore) on [algooci/tracim](https://hub.docker.com/r/algooci/tracim/tags) has been added, CI will run on this tag for this branch.

Remove tag specification `concourse/pipelines/pull-request.yml` (line 63) before merging !

**Comment by Millefeuille42** [comment]
Changed how dependencies are managed in the separate requirements file.
They are created one per extra along with main dependencies.

This permits to use `pip`/`pip-compile` toolchains on every requirements file instead of just `requirements.txt`. I also added a handy script in `.../backend/set_requirements.bash` that will create (or update with the `-U` flag) all requirements files.

This means that we only have to maintain `setup.py` to add, remove or update dependencies.

**Comment by PhilippeAccorsi** [comment]
@Millefeuille42 il me semble que le support de mysql / mariadb n'est plus assuré pour tracim (cf changelog de mémoire). Peut-être qu'il y a des éléments pour lesquel il n'y a plus rien à faire, sauf du ménage `backend/requirements-db-mysql.txt
`.

En tout cas par le passé, j'ai souvenir que l'on avait communiqué sur la fin du support de ce type de bdd.

**Comment by Millefeuille42** [comment]
Updated all non-breaking dependencies.

Froze version of 
- sqlakeyset, because it's API changed
- elasticsearch, because latest versions are not necessarily compatible with the versions of ES we use, and the API changed.

Did the same for dev tools (lint) because rules change when updating and we would have to edit all of our code if we did so.

**Comment by Millefeuille42** [comment]
An intermediary PR from [dafda15](https://github.com/tracim/tracim/pull/6426/commits/dafda156614f5688e84cc7228ef705b7bfeaccaa) has been created to upgrade python version as soon as possible. (#6495)
This PR is now focused on upgrading the dependencies instead of the python versions. Since it doesn't match it's original issue, a new branch and PR will be created.

**Pull request closed without merging**
