### PR TITLE
remove content_filter from sidebar entries

### PR DESCRIPTION
**Pull request by inkhey**
related to #3627 

## Checkpoints

**For developers**

- [x] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [x] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
- [x] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)

**For code reviewers**

- [x] The code is clear enough
- [x] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [x] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [x] Manual, quality tests have been done

### CODE REVIEW

**Comment by inkhey** [comment]
to test this:
- Check if content filter are visible in "sidebar" .they should not more being visible only dashboard, all-content, gallery and agenda should be visible (depending on active app)

**Review by raphj — APPROVED** [review]

**Comment by grignards** [comment]
Tested on branch.

**Comment by grignards** [comment]
@inkhey BTW, did you create this PR as inkhey voluntarily? Or should asf-algoo be the author?

**Comment by inkhey** [comment]
> @inkhey BTW, did you create this PR as inkhey voluntarily? Or should asf-algoo be the author?

You right it's a mistake.

**Pull request closed without merging**
