### PR TITLE
feat: Exclude emojis from byLabel sorting

### PR DESCRIPTION
**Pull request by Millefeuille42**
#6357 

## Checkpoints

**For developers**

- [x] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [x] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
- [x] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)
- [x] Make sure that:
  - if there are modifications in the Tracim configuration files (eg. `development.ini`), they are documented in `backend/doc/setting.md`
  - any migration process required for existing instances is documented
  - relevant people for these changes are notified
- [x] Original authors of the features included in a multi-feature branch (maintenance fixes -> develop, security fixes -> develop, …) should be part of the reviewers, especially if you encountered merge conflicts.

**For code reviewers**

- [x] The code is clear enough
- [x] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [x] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [x] Manual, quality tests have been done

### CODE REVIEW

**Review by Skylsmoi — APPROVED** [review]

**Review by Skylsmoi — CHANGES_REQUESTED** [review]
good
try to add the regex to configEnv.json, if it's any trouble, give up and merge as is

**Comment by Millefeuille42** [comment]
@Skylsmoi Not really sure this is possible, since the helper function it is based on is in frontend_lib. A solution for this is to re-sort in the workspace list component, but that would be too much IMO.

**Comment by Skylsmoi** [comment]
mmh indeed
let's not do that then

**Comment by Millefeuille42** [comment]
For the tester:
1. Create several workspace, some must have emojis in front of their name (e.g. '🦊 My workspace')
2. They should be sorted alphabetically (a to z) without considering the emojis.
3. Other non ascii common characters such as accents should be considered in the sort.

Note: ASCII symbols such as `<>/?` and such are considered as valid by the sort.

**Review by Skylsmoi — APPROVED** [review]

**Comment by Skylsmoi** [comment]
tested on branch

**Pull request merged**
