### PR TITLE
fix(backend): user username instead of public name

### PR DESCRIPTION
**Pull request by Haskaris**
No Issue related

## Checkpoints

**For developers**

- [x] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
~~- [ ] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution~~
~~- [ ] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)~~
- [x] Make sure that:
  - if there are modifications in the Tracim configuration files (eg. `development.ini`), they are documented in `backend/doc/setting.md`
  - any migration process required for existing instances is documented
  - relevant people for these changes are notified
- [x] Original authors of the features included in a multi-feature branch (maintenance fixes -> develop, security fixes -> develop, …) should be part of the reviewers, especially if you encountered merge conflicts.

**For code reviewers**

- [x] The code is clear enough
- [x] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [x] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [x] Manual, quality tests have been done

### CODE REVIEW

**Review by Millefeuille42 — APPROVED** [review]

**Comment by PhilippeAccorsi** [comment]
I think this fix is a bugfix for tracim 4.5.x so maybe better to merge in maintenance branch.

**Comment by Haskaris** [comment]
Indeed. However the maintenance branch doesn't exist yet. If you can create it I can change the destination branch.

**Comment by Haskaris** [comment]
PR updated

**Comment by PhilippeAccorsi** [comment]
Need to create a related issue to follow this topic

**Comment by lebouquetin** [comment]
@buxx @Skylsmoi : could you review (or test) this and merge it into develop in order to close the branch. Or should I merge it directly? (there is one line to review/test/deliver)

**Comment by Skylsmoi** [comment]
I'm gonna test it

**Comment by Skylsmoi** [comment]
tested on branch

**Pull request merged**
