### PR TITLE
[For 2.6.x] Faster retrieval of frontend dependencies, without sudo

### LINKED ISSUE #2747: Installing frontend dependencies is slow and requires being root
See #2916 for a comprehensive explanation about the migration to Yarn, that fixes this issue.

## Bug description & symptom

The script to install frontend dependencies runs npm install several times, leading  to duplicate downloads of dependencies.

The npm link also requires being root to build Tracim.

## Diagnostic

Run: ./install_frontend_dependencies.sh

## Expected

Each dependency is not downloaded more than once.
Root is not required to install the dependencies is all the system dependencies (Debian packages) are already there.

## Context and version information

tracim develop branch (984d624f53ea25ffa5aa16ead91b297d39165268) and up-to-date Debian Buster

## Prerequisites

This issue does not depend on any other issue 

## Impacted components

The build system

## Extra information

The following pull request fixes this issue: #2873

### PR DESCRIPTION
**Pull request by raphj**
This pull request fixes #2747.

- It centralises `node_modules` folders scattered across the parts for the
  frontend (frontend, frontend_lib, apps) in one place, and use symbolic links
  for the node_modules of each project to the shared node_modules folder.
  This allows speeding up the retrieval of node dependencies a lot.
    
  A script builds a super `package.json` from all the packages.json files of
  the frontend folders, ensuring that the versions of the dependencies are all
  compatible with each other. This file is stored in an hidden folder:
  `.frontend-apps-node-modules`
    
- It gets rid of `npm link` in favor a raw symbolic link, removing the need to be
   root to build Tracim (except for installing the system dependencies).

One caveat is that running `npm instal`l in one of the frontend-related folders, the `tracim_frontend_lib` symbolic link is removed from the `node_modules` folder. This is easily fixed by re-creating the symbolic link.

Related issue? #2747 

## Checkpoints

- [x] Code is clear enough
- [x] If there are FIXME in the code, then there are associated issues and issue is referenced in the FIXME
- [x] If there are TODO, NOTE or HACK in code, date and developer initials are present
- [x] Automated tests have been written (covering feature or non regression), or *at least* an issue has been created for test implementation

- [ ] Tested by quality team

### CODE REVIEW

**Comment by raphj** [comment]
I just built the Docker image with these changes. It works.

**Comment by Skylsmoi** [comment]
I think we'll need to talk about this PR, it might be a bit too complicated for a simple review

**Comment by raphj** [comment]
@bux your wishes are orders milord. I turned function comments into proper doc strings

@Skylsmoi I am ready to speak about this pull request with you and anybody who wants to participate any time :-)

**Comment by bux** [comment]
wat?

**Comment by raphj** [comment]
sorry @bux, I meant to call @buxx and made a typo

**Comment by Skylsmoi** [comment]
As discussed with @raphj , we won't improve this PR until we have looked into builtin options to do similar process using npm or yarn.
Main feature to look into in yarn's workspaces

**Comment by raphj** [comment]
A cleaner pull request replacing npm by yarn and its workspaces feature is coming.

**Comment by PhilippeAccorsi** [comment]
Can you add some comment in issue ? And changing column from in merge request to "to do".

**Pull request closed without merging**
