### PR TITLE
doc: change travis status url

### PR DESCRIPTION
**Pull request by PhilippeAccorsi**
Replace travis status url to show real status of CI used by tracim since migratation from travis-ci.org to travis-ci.com [skip ci]

## Checkpoints

**For developers**

- [x] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [x] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
- [x] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link)

**For code reviewers**

- [x] The code is clear enough
- [x] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [x] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [x] Manual, quality tests have been done

### CODE REVIEW

**Comment by PhilippeAccorsi** [comment]
No test necessary here.

**Comment by PhilippeAccorsi** [comment]
Maybe we can find and change also here the url of scrutinizer-ci.com to show usable status. At present it scrutinizer not seems working (last information have more than 2 years)

**Comment by PhilippeAccorsi** [comment]
This seem to be broken also https://coveralls.io/github/tracim/tracim?branch=develop

**Review by raphj — APPROVED** [review]

**Comment by PhilippeAccorsi** [comment]
I think we can merge this fix now. 
scrutinizer and coveralls not work but need more research to understand what is going on.

**Pull request merged**
