### PR TITLE
Refactor unit tests of frontend and frontend_lib

### PR DESCRIPTION
**Pull request by metzgegu**
#2663 

## Checkpoints

The goal of this section is to help code reviewer to do required checks on this pull request. Please don't edit this list.
If one or more of these checkpoints are out of scope, please write below why they are.

- [x] Code is clear enough
- [x] If there are FIXME in the code, then there are associated issues and issue is referenced in the FIXME
- [x] If there are TODO, NOTE or HACK in code, date and developer initials are present
- [x] Automated tests have been written (covering feature or non regression), or *at least* an issue has been created for test implementation

- [x] Tested by quality team

### CODE REVIEW

**Comment by Skylsmoi** [comment]
@PhilippeAccorsi To test this PR, run the unit test of frontend and frontend_lib locally. Check that everything is green (no failed test) and that there is no linting warning

@metzgegu @PhilippeAccorsi This PR is a very good start. Although, I have a few more indications on what to refactor regarding frontend and frontend_lib unit tests. Should we keep this issue/PR and add some todos or should we create a new issue ?

**Comment by PhilippeAccorsi** [comment]
I can see error
~~~
> tracim@1.0.0 test /home/philippe/repo/tracim/frontend
> (standard --env mocha "test/**/*.js" || echo "
Some Linting error") && NODE_ENV=test mocha --config test/.mocharc.js
~~~
I have just try this command in my local repo `./run_frontend_unit_test.sh` (not starting install frontend script and not starting build script)

**Comment by Skylsmoi** [comment]
@PhilippeAccorsi What you quoted is the actual command line that is being executed : ] so that is not an error.
explanations:
```
(standard --env mocha "test/**/*.js" ||       # this is the command that start the linter (which is standard)
echo "Linting error") &&                      # this is the output in shell in case there is any warnings or errors
NODE_ENV=test mocha --config test/.mocharc.js # this is the command that starts the unit tests
```

Also, when running frontend unit tests, you don't need to build the apps. Only the dependencies are required (install_frontend_dependencies.sh) but since there are no new ones in this PR, it's actually optional.

**Comment by PhilippeAccorsi** [comment]
Ok. so thats ok for me.
Just wait to merge (we need to create stable release of 2.6.0 first).

**Pull request merged**
