### PR TITLE
feat: add arabic language

### PR DESCRIPTION
**Pull request by grignards**
And integrate language direction.

See #5288.

-------

## Checkpoints

**For developers**

- [x] If relevant, manual tests have been done to ensure the stability of the whole application and that the involved feature works
- [x] The original issue is up to date w.r.t the latest discussions and contains a short summary of the implemented solution
- [x] Automated tests covering the feature or the fix, have been written, deemed irrelevant (give the reason), or an issue has been created to implement the test (give the link): there are no automated tests for language selection
- [x] Make sure that:
  - if there are modifications in the Tracim configuration files (eg. `development.ini`), they are documented in `backend/doc/setting.md`
  - any migration process required for existing instances is documented
  - relevant people for these changes are notified
- [x] Original authors of the features included in a multi-feature branch (maintenance fixes -> develop, security fixes -> develop, …) should be part of the reviewers, especially if you encountered merge conflicts.

**For code reviewers**

- [x] The code is clear enough
- [x] If there are FIXMEs in the code, related issues are mentioned in the FIXME
- [x] If there are TODOs, NOTEs or HACKs in code, the date and the developer initials are present

**For testers**

- [x] Manual, quality tests have been done

### CODE REVIEW

**Review by knodelle — APPROVED** [review]

**Comment by gbonaspetti** [comment]
Should we add something at `frontend/src/component/Search/DateFilter.jsx`?

**Comment by grignards** [comment]
> * Should we add something at `frontend/src/component/Search/DateFilter.jsx`?
I'd say yes, I'll add arabic with `__NOT_TRANSLATED__` placeholders for now.
> 
>     * Missing add arabic to `frontend/src/util/tinymceInit.js` if available


> 
>     * Add/check if collaborative software is available in this language, if not, some information about that need to be added in project. (ref [Feat: add documentation about how to add new translation in Tracim #3003](https://github.com/tracim/tracim/issues/3003))

There is at least some support of arabic in collabora (translation files exist for the language), is there something special to do in the app's code to support it?

**Comment by grignards** [comment]
> > * Should we add something at `frontend/src/component/Search/DateFilter.jsx`?
I'd say yes, I'll add arabic with `__NOT_TRANSLATED__` placeholders for now.
> >   
> >   * Missing add arabic to `frontend/src/util/tinymceInit.js` if available
Will do.
> > ```
> > * Add/check if collaborative software is available in this language, if not, some information about that need to be added in project. (ref [Feat: add documentation about how to add new translation in Tracim #3003](https://github.com/tracim/tracim/issues/3003))
> > ```
> 
> There is at least some support of arabic in collabora (translation files exist for the language), is there something special to do in the app's code to support it?

**Review by gbonaspetti — APPROVED** [review]

**Comment by knodelle** [comment]
tested on branch

**Pull request merged**
