### PR TITLE
WIP rename collaborative document edition app

### PR DESCRIPTION
**Pull request by inkhey**
related to #2156 

## Checkpoints

The goal of this section is to help code reviewer to do required checks on this pull request. Please don't edit this list.
If one or more of these checkpoints are out of scope, please write below why they are.

- [x] Code is clear enough
- [x] If there are FIXME in the code, then there are associated issues and issue is referenced in the FIXME
- [x] If there are TODO, NOTE or HACK in code, date and developer initials are present
- [x] Automated tests have been written (covering feature or non regression), or *at least* an issue has been created for test implementation

### CODE REVIEW

**Comment by inkhey** [comment]
in draft because waiting for frontend dev.

**Comment by PhilippeAccorsi** [comment]
Do not merge.

**Comment by PhilippeAccorsi** [comment]
@inkhey delete this branch if you are ok with @Skylsmoi branch (about cherry pick and new branch created for this issue).

**Comment by inkhey** [comment]
replaced by ****

**Pull request closed without merging**
