### PR TITLE
Example docker compose

### PR DESCRIPTION
**Pull request by uggla**

### CODE REVIEW

**Comment by buxx** [comment]
Looks ok. @PhilippeAccorsi  Can you plan to test it ? If ok i suggest to open issue to add reference to this file in documentation.

**Comment by PhilippeAccorsi** [comment]
@buxx do you have open issue about that?

**Comment by buxx** [comment]
@PhilippeAccorsi No i don't.

**Comment by PhilippeAccorsi** [comment]
Ok.
Tested and verified.

**Pull request merged**
